version: "3.8"
services:
  redis:
    image: redis:7.2.2-alpine
    restart: on-failure

  mongodb:
    image: mongo:7.0.2
    restart: on-failure
    healthcheck:
      test: echo 'db.state().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  frontend:
    build: ./frontend
    image: openagents-frontend
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongodb
      - backend

# Necessary if you want the code executed in sandbox
  # code_interpreter:
  #   image: xlanglab/xlang-code-interpreter-python
  #   env_file:
  #     - ./real_agents/data_agent/.code_interpreter_docker_env
  #   volumes:
  #     - backend-data:/home
  #   cap_add:
  #     - SYS_RESOURCE
  #     - SYS_PTRACE
  #     - NET_ADMIN

  backend:
    build: ./
    image: openagents-backend
    ports:
      - 8000:8000
    depends_on:
      - redis
      - mongodb
    volumes:
      - "backend-data:/app/backend/data"
    environment:
      - OPENAI_API_KEY= #need your key here
      # - OPENAI_API_BASE=
      - REDIS_SERVER=redis
      - MONGO_SERVER=mongodb
      - CODE_INTER_SERVER=code_interpreter
      - CODE_EXECUTION_MODE=local #if code_interpreter running set docker,else local
    # if you want to use gpu, uncomment the following lines
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         device_ids: ['0']
    #         capabilities: [gpu]

volumes:
  backend-data:
    driver: local
