path_dict = {
    "bilibili_subtitle": "/bilibili/subtitle",
    "get_video_info": "/bilibili/video",
    "douyin_user_info": "/douyin/user",
    "get_DouyinVideos": "/douyin/videos",
    "github_repos": "/github/repos",
    "get_new_stories": "/hackernews/latest",
    "get_top_stories": "/hackernews/top",
    "huobi_kline": "/huobi/kline",
    "ikea_recommend": "/ikea/recommend",
    "recently_movies": "/maoyan/recently",
    "music_lyric": "/music/lyric",
    "music_search": "/music/search",
    "search_podcasts": "/podcasts/search",
    "uniqlo_stylingbook": "/uniqlo/stylingbook",
    "v2ex_latest": "/v2ex/latest",
    "v2ex_trending": "/v2ex/trending",
    "get_weather_today": "/weather/today",
    "weibo_trending": "/weibo/trending",
    "youdao_fanyi": "/youdao/fanyi",
    "youtube_user": "/youtube/user",
    "youtube_video": "/youtube/video",
    "top_questions": "/zhihu/questions",
    "zhihu_trending": "/zhihu/trending",
}
